export const ERROR_MESSAGES_MAP: Record<string, string> = {
  // Common
  'Validation error': 'Lỗi dữ liệu đầu vào',

  // USERS_MESSAGES
  'Name is required': 'Vui lòng nhập tên',
  'Name must be between 2 and 100 characters long': 'Tên phải từ 2 đến 100 ký tự',
  'Name must be a string': 'Tên phải là chuỗi ký tự',
  'Email already exists': 'Email này đã được sử dụng. Vui lòng dùng email khác.',
  'Email is required': 'Vui lòng nhập email',
  'Email or password is not correct': 'Email hoặc mật khẩu không chính xác',
  'Invalid email format': 'Định dạng email không hợp lệ',
  'Password is required': 'Vui lòng nhập mật khẩu',
  'Password must be at least 6 characters': 'Mật khẩu phải có ít nhất 6 ký tự',
  'Password must contain at least one uppercase letter, one lowercase letter, and one number':
    'Mật khẩu phải chứa ít nhất 1 chữ hoa, 1 chữ thường và 1 số',
  'Password must be a string': 'Mật khẩu phải là chuỗi ký tự',
  'Password must be between 6 and 50 characters long': 'Mật khẩu phải từ 6 đến 50 ký tự',
  'Passwords do not match': 'Mật khẩu không khớp',
  'Confirm password is required': 'Vui lòng xác nhận mật khẩu',
  'Confirm password must be a string': 'Mật khẩu xác nhận phải là chuỗi ký tự',
  'Confirm password must be between 6 and 50 characters long': 'Mật khẩu xác nhận phải từ 6 đến 50 ký tự',
  'Confirm password do not match': 'Mật khẩu xác nhận không khớp',
  'Date of birth is required': 'Vui lòng nhập ngày sinh',
  'Date of birth must be a string': 'Ngày sinh phải là chuỗi',
  'Date of birth must be in the past': 'Ngày sinh phải trong quá khứ',
  'Date must be in ISO 8601 format': 'Ngày không đúng định dạng ISO 8601',
  'Login successful': 'Đăng nhập thành công',
  'Login failed': 'Đăng nhập thất bại',
  'Registration successful': 'Đăng ký thành công',
  'Registration failed': 'Đăng ký thất bại',
  'Check email exists failed': 'Không thể kiểm tra email. Vui lòng thử lại.',
  'User not found': 'Không tìm thấy người dùng',
  'Email not found': 'Email không tồn tại trong hệ thống',
  'User not verified. Please verify your email first': 'Tài khoản chưa được xác thực. Vui lòng kiểm tra email.',
  'User account is banned': 'Tài khoản của bạn đã bị khóa.',
  'Current password is incorrect': 'Mật khẩu hiện tại không đúng',
  'Old password is incorrect': 'Mật khẩu hiện tại không đúng',
  'Change password successful': 'Đổi mật khẩu thành công',
  'Gmail account is not verified': 'Tài khoản Gmail chưa được xác thực.',
  'Phone number must be a string': 'Số điện thoại phải là chuỗi',
  'Phone number must be between 10 and 15 characters': 'Số điện thoại phải từ 10 đến 15 số',
  'Gender must be 0 or 1': 'Giới tính không hợp lệ',
  'Address must be an object': 'Địa chỉ không hợp lệ',
  'Address is invalid': 'Địa chỉ không hợp lệ',
  'Ward is invalid': 'Phường/Xã không hợp lệ',
  'City is invalid': 'Tỉnh/Thành phố không hợp lệ',

  // Token
  'Access token is required': 'Thiếu Access Token',
  'Invalid access token': 'Access Token không hợp lệ',
  'Refresh token is required': 'Thiếu Refresh Token',
  'Invalid refresh token': 'Refresh Token không hợp lệ',
  'Used refresh token or not exists': 'Refresh Token đã được sử dụng hoặc không tồn tại',
  'Email verify token is required': 'Thiếu token xác thực email',
  'Invalid email verify token': 'Token xác thực email không hợp lệ',
  'Email already verified before': 'Email đã được xác thực trước đó',
  'Email verification successful': 'Xác thực email thành công',
  'Resend email verification successful': 'Đã gửi lại email xác thực',
  'Forgot password token is required': 'Thiếu token quên mật khẩu',
  'Invalid forgot password token': 'Token quên mật khẩu không hợp lệ',
  'Reset password token is required': 'Thiếu token đặt lại mật khẩu',
  'Invalid reset password token': 'Token đặt lại mật khẩu không hợp lệ hoặc đã hết hạn',
  'Verify forgot password token successful': 'Token đặt lại mật khẩu hợp lệ',
  'Reset password successful': 'Đặt lại mật khẩu thành công',
  'Reset password failed': 'Đặt lại mật khẩu thất bại',
  'Token refresh failed': 'Phiên đăng nhập đã hết hạn. Vui lòng đăng nhập lại.',
  'Email verification failed': 'Xác thực email thất bại. Token có thể đã hết hạn.',
  'Failed to resend verification email': 'Không thể gửi lại email xác thực. Vui lòng thử lại.',
  'Invalid token': 'Token không hợp lệ hoặc đã hết hạn.',
  'Failed to send reset password email': 'Không thể gửi email đặt lại mật khẩu. Vui lòng thử lại.',
  'Password reset failed': 'Đặt lại mật khẩu thất bại. Vui lòng thử lại.',
  'Password change failed': 'Đổi mật khẩu thất bại. Vui lòng thử lại.',
  'Profile update failed': 'Cập nhật hồ sơ thất bại. Vui lòng thử lại.',
  'Failed to get user profile': 'Không thể tải thông tin tài khoản.',

  // Products & Carts
  'Product not found': 'Không tìm thấy sản phẩm',
  'Insufficient stock quantity': 'Số lượng tồn kho không đủ',
  'Cart is empty': 'Giỏ hàng trống',
  'Product ID is required': 'Thiếu ID sản phẩm',
  'Quantity is required': 'Vui lòng nhập số lượng',
  'Quantity must be a positive number': 'Số lượng phải là số dương',
  'Quantity must be between 1 and 10': 'Số lượng phải từ 1 đến 10',
  'Cart item not found': 'Không tìm thấy sản phẩm trong giỏ hàng',

  // Orders
  'Order not found': 'Không tìm thấy đơn hàng',
  'Invalid order status': 'Trạng thái đơn hàng không hợp lệ',
  'Phone number is required': 'Vui lòng nhập số điện thoại',
  'Address is required': 'Vui lòng nhập địa chỉ',
  'Ward is required': 'Vui lòng nhập Phường/Xã',
  'District is required': 'Vui lòng nhập Quận/Huyện',
  'Province is required': 'Vui lòng nhập Tỉnh/Thành phố',
  'Payment method is required': 'Vui lòng chọn phương thức thanh toán',
  'Shipping address is required': 'Vui lòng nhập địa chỉ giao hàng',
  'First name is required': 'Vui lòng nhập tên',
  'Last name is required': 'Vui lòng nhập họ',

  // Categories
  'Category not found': 'Không tìm thấy danh mục',

  // Brands
  'Brand not found': 'Không tìm thấy thương hiệu',
}

export const getErrorMessage = (message: string): string => {
  return ERROR_MESSAGES_MAP[message] || message
}
