import type { User, Order, Address, Prescription } from '../types/account'

export const mockUser: User = {
  id: 'user-1',
  email: 'customer@medispace.com',
  firstName: 'Nguyễn',
  lastName: 'Văn A',
  phone: '0123456789',
  avatar: '/images/user-avatar.jpg',
  dateOfBirth: '1990-05-15',
  gender: 'male',
  membershipLevel: 'gold',
  loyaltyPoints: 1450,
  totalSaved: 850000,
  joinDate: '2022-03-15T00:00:00Z',
  medicalInfo: {
    bloodType: 'O+',
    allergies: ['Penicillin', 'Peanuts'],
    chronicConditions: ['Cao huyết áp'],
    emergencyContact: {
      name: 'Nguyễn Thị B',
      phone: '0987654321',
      relationship: 'Vợ',
    },
  },
}

export const mockAddresses: Address[] = [
  {
    id: 'addr-1',
    userId: 'user-1',
    type: 'home',
    recipientName: 'Nguyễn Văn A',
    phone: '0123456789',
    addressLine1: '123 Đường Nguyễn Trãi',
    addressLine2: 'Chung cư Vinhomes',
    ward: 'Phường Bến Thành',
    district: 'Quận 1',
    city: 'TP. Hồ Chí Minh',
    postalCode: '70000',
    isDefault: true,
    label: 'Nhà riêng',
  },
  {
    id: 'addr-2',
    userId: 'user-1',
    type: 'office',
    recipientName: 'Nguyễn Văn A',
    phone: '0123456789',
    addressLine1: '456 Đường Lê Lợi',
    ward: 'Phường Bến Nghé',
    district: 'Quận 1',
    city: 'TP. Hồ Chí Minh',
    postalCode: '70000',
    isDefault: false,
    label: 'Văn phòng',
  },
]

export const mockOrders: Order[] = [
  {
    id: 'order-1',
    customerId: 'user-1',
    orderNumber: 'DH001234',
    status: 'shipping',
    items: [
      {
        id: 'item-1',
        productId: '1',
        productName: 'Paracetamol 500mg',
        productImage: '/images/paracetamol.jpg',
        brand: 'Traphaco',
        unit: 'Hộp 10 viên',
        quantity: 2,
        unitPrice: 20000,
        subtotal: 40000,
        isPrescription: false,
      },
      {
        id: 'item-2',
        productId: '2',
        productName: 'Vitamin C 1000mg Blackmores',
        productImage: '/images/vitamin-c.jpg',
        brand: 'Blackmores',
        unit: 'Hộp 60 viên',
        quantity: 1,
        unitPrice: 380000,
        subtotal: 380000,
        isPrescription: false,
      },
    ],
    subtotal: 420000,
    shippingFee: 30000,
    discount: 0,
    total: 450000,
    shippingAddress: mockAddresses[0],
    paymentMethod: 'COD',
    paymentStatus: 'pending',
    createdAt: '2024-01-15T14:30:00Z',
    updatedAt: '2024-01-16T08:15:00Z',
    estimatedDelivery: '2024-01-16T18:00:00Z',
    trackingNumber: 'VN123456789',
    deliveryMethod: 'Giao hàng tiêu chuẩn',
    timeline: [
      {
        id: 't1',
        status: 'confirmed',
        statusText: 'Đặt hàng thành công',
        timestamp: '2024-01-15T14:30:00Z',
        description: 'Đơn hàng đã được xác nhận',
        isCompleted: true,
      },
      {
        id: 't2',
        status: 'processing',
        statusText: 'Xác nhận đơn hàng',
        timestamp: '2024-01-15T14:45:00Z',
        description: 'Đơn hàng đang được xử lý',
        isCompleted: true,
      },
      {
        id: 't3',
        status: 'preparing',
        statusText: 'Đang chuẩn bị hàng',
        timestamp: '2024-01-15T16:20:00Z',
        description: 'Hàng đang được đóng gói',
        isCompleted: true,
      },
      {
        id: 't4',
        status: 'shipping',
        statusText: 'Đang vận chuyển',
        timestamp: '2024-01-16T08:15:00Z',
        description: 'Đơn hàng đang trên đường giao',
        isCompleted: true,
      },
      {
        id: 't5',
        status: 'delivered',
        statusText: 'Giao hàng thành công',
        timestamp: '',
        description: 'Dự kiến giao hàng',
        isCompleted: false,
      },
    ],
  },
  {
    id: 'order-2',
    customerId: 'user-1',
    orderNumber: 'DH001235',
    status: 'delivered',
    items: [
      {
        id: 'item-3',
        productId: '3',
        productName: 'Amoxicillin 500mg',
        productImage: '/images/amoxicillin.jpg',
        brand: 'Stada',
        unit: 'Hộp 20 viên',
        quantity: 1,
        unitPrice: 45000,
        subtotal: 45000,
        isPrescription: true,
      },
    ],
    subtotal: 45000,
    shippingFee: 30000,
    discount: 5000,
    total: 70000,
    shippingAddress: mockAddresses[0],
    paymentMethod: 'Banking',
    paymentStatus: 'paid',
    createdAt: '2024-01-10T10:00:00Z',
    updatedAt: '2024-01-12T16:00:00Z',
    trackingNumber: 'VN987654321',
    deliveryMethod: 'Giao hàng nhanh',
    prescriptionId: 'pres-1',
    timeline: [
      {
        id: 't6',
        status: 'confirmed',
        statusText: 'Đặt hàng thành công',
        timestamp: '2024-01-10T10:00:00Z',
        isCompleted: true,
      },
      {
        id: 't7',
        status: 'delivered',
        statusText: 'Đã giao hàng',
        timestamp: '2024-01-12T16:00:00Z',
        description: 'Giao hàng thành công',
        isCompleted: true,
      },
    ],
  },
  {
    id: 'order-3',
    customerId: 'user-1',
    orderNumber: 'DH001236',
    status: 'pending_payment',
    items: [
      {
        id: 'item-4',
        productId: '5',
        productName: 'Ibuprofen 400mg',
        productImage: '/images/ibuprofen.jpg',
        brand: 'Abbott',
        unit: 'Hộp 20 viên',
        quantity: 3,
        unitPrice: 28000,
        subtotal: 84000,
        isPrescription: false,
      },
    ],
    subtotal: 84000,
    shippingFee: 30000,
    discount: 10000,
    total: 104000,
    shippingAddress: mockAddresses[1],
    paymentMethod: 'Banking',
    paymentStatus: 'pending',
    createdAt: '2024-01-18T09:30:00Z',
    updatedAt: '2024-01-18T09:30:00Z',
    deliveryMethod: 'Giao hàng tiêu chuẩn',
    timeline: [
      {
        id: 't8',
        status: 'pending_payment',
        statusText: 'Chờ thanh toán',
        timestamp: '2024-01-18T09:30:00Z',
        description: 'Vui lòng thanh toán để xử lý đơn hàng',
        isCompleted: false,
      },
    ],
  },
]

export const mockPrescriptions: Prescription[] = [
  {
    id: 'pres-1',
    customerId: 'user-1',
    prescriptionNumber: 'DT001',
    doctorName: 'BS. Trần Văn D',
    hospital: 'BV Chợ Rẫy',
    prescriptionDate: '2024-01-08',
    images: ['/images/prescription1.jpg', '/images/prescription2.jpg'],
    medicines: [
      {
        id: 'med-1',
        name: 'Amoxicillin 500mg',
        dosage: '500mg',
        frequency: '2 viên/ngày',
        duration: '7 ngày',
        instructions: 'Uống sau ăn',
        quantity: 14,
      },
      {
        id: 'med-2',
        name: 'Paracetamol 500mg',
        dosage: '500mg',
        frequency: '1 viên khi sốt',
        duration: 'Theo triệu chứng',
        instructions: 'Không quá 3 lần/ngày',
      },
    ],
    status: 'completed',
    pharmacistId: 'pharmacist-1',
    pharmacistNotes: 'Đơn thuốc hợp lệ. Đã tạo đơn hàng cho khách hàng.',
    contactPhone: '0123456789',
    notes: 'Viêm họng, sốt nhẹ',
    createdAt: '2024-01-08T16:30:00Z',
    updatedAt: '2024-01-10T09:45:00Z',
    orderId: 'order-2',
  },
  {
    id: 'pres-2',
    customerId: 'user-1',
    prescriptionNumber: 'DT002',
    doctorName: 'BS. Lê Thị E',
    hospital: 'BV Bình Dân',
    prescriptionDate: '2024-01-15',
    images: ['/images/prescription3.jpg'],
    medicines: [
      {
        id: 'med-3',
        name: 'Lisinopril 10mg',
        dosage: '10mg',
        frequency: '1 viên/ngày',
        duration: '30 ngày',
        instructions: 'Uống vào buổi sáng',
        quantity: 30,
      },
    ],
    status: 'pending',
    contactPhone: '0123456789',
    notes: 'Cao huyết áp, cần theo dõi',
    createdAt: '2024-01-15T10:15:00Z',
    updatedAt: '2024-01-15T10:15:00Z',
  },
  {
    id: 'pres-3',
    customerId: 'user-1',
    prescriptionNumber: 'DT003',
    doctorName: 'BS. Phạm Văn F',
    hospital: 'BV Đại học Y Dược',
    prescriptionDate: '2024-01-12',
    images: ['/images/prescription4.jpg'],
    medicines: [
      {
        id: 'med-4',
        name: 'Metformin 500mg',
        dosage: '500mg',
        frequency: '2 viên/ngày',
        duration: '60 ngày',
        instructions: 'Uống cùng bữa ăn',
      },
    ],
    status: 'rejected',
    pharmacistId: 'pharmacist-1',
    pharmacistNotes: 'Đơn thuốc không rõ ràng. Vui lòng gửi lại ảnh rõ hơn.',
    rejectionReason: 'Hình ảnh đơn thuốc không rõ ràng',
    contactPhone: '0123456789',
    notes: 'Tiểu đường type 2',
    createdAt: '2024-01-12T14:20:00Z',
    updatedAt: '2024-01-13T11:30:00Z',
  },
]

// mockNotifications removed — notifications should come from backend via notificationService.
// Keep other mock data (users, orders, prescriptions) for domains the backend does not yet support.
